# Book settings
title: "Study Workflow Orchestration with Airflow"
author: TIGR CATS
copyright: "2021"

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab

repository:
  url: https://github.com/tigrlab/air-tigrs
  path_to_book: docs
  branch: main

# Set sphinx extensions for build
sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
